### ISSUE TITLE
Congestion support

### ISSUE THREAD

**Issue by telezhnaya** [Near-One/transaction-bench#2]
I expect hitting the timeout during congestions.

We need to ask for the tx status after the timeout error
The total waiting time should include tx status request as well.

**Comment by Trisfald** [comment]
Is it possible to hit the timeout and still have a successful transaction?

Also we could add another metric counter for transactions that went into timeout.

**Comment by telezhnaya** [comment]
> Is it possible to hit the timeout and still have a successful transaction?

Yes

It's almost always the case
